name: backend-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - boto3
  - libcxx
  - python-dotenv
  - docker-py
  - flake8
  - isort
  - pre-commit
  - pip
  - pip:
      - /Users/dman/Documents/code/hummingbot/dist/hummingbot-20250303-cp312-cp312-macosx_11_0_arm64.whl
      - git+https://github.com/hummingbot/hbot-remote-client-py.git
