name: backend-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - boto3
  - libcxx
  - python-dotenv
  - docker-py
  - pip
  - pip:
      - hummingbot
      - flake8
      - isort
      - pre-commit
      - logfire
      - logfire[fastapi]
      - logfire[system-metrics]
      - aiomqtt>=2.0.0
